### PR TITLE
plugins parameter undef

### PR DESCRIPTION
**Pull request by tiernap**
set plugins parameter to undef as default to not set (empty) $config['plugins'] array in roundcube config . useful where one wishes to manage plugins outside of this module.

### CODE REVIEW

**Comment by tohuwabohu** [comment]
> useful where one wishes to manage plugins outside of this module.

Whilst I don't object to overall goal this looks like an anti-pattern: the responsibility for the configuration is scattered across multiple places. Also the special behaviour of `undef` vs. an empty list sounds like a nasty trap.

Can you please quickly summarize what's missing in this module to support your use case out of the box?

**Comment by tiernap** [comment]
hi, thank you for responding.

the goal is to not have the module write $config['plugins'] on empty plugins array. if i dont set the plugins parameter, the module still writes the following to config file:

`$config['plugins'] = array()`

this is causing me problems with a roundcube plugin that i manage outside of this module.

but, i do now see my pull request is badly written (please excuse). i only need to add:

```
if !empty($roundcube::plugins) {
  concat::fragment { "${config_file}__plugins_head":
```
to config.pp . ill resubmit a better written pull request and it should be more obvious.

thank you

**Comment by tohuwabohu** [comment]
I presume with #12 in place you add your own concat fragment to manage the plugin? Or how do things get composed together? I still struggle to understand how this can be useful...

**Comment by tiernap** [comment]
i define plugins in the config_file_template, without #12 this module adds the empty plugins variable also to config.inc.php thus thrashing my declaration. then elsewhere i copy the plugin folder (a legacy plugin developed internally)

thank you

**Pull request closed without merging**
