### PR TITLE
added check for empty plugins variable

### PR DESCRIPTION
**Pull request by tiernap**
added check for plugins variable before writing to config.inc.php

### CODE REVIEW

**Comment by tiernap** [comment]
added same if condition as with options parameter (dont write to config.inc.php if plugins is empty)

**Comment by tohuwabohu** [comment]
Looks all good. I'm making the assumption that roundcube can handle the absence of the explicit plugins array in the config file and will use a sane default. Otherwise this would be a breaking change.

**Comment by tohuwabohu** [comment]
Whilst writing the changlelog my memories came back and I realized I have more questions about this change. Asked on #11 .

**Comment by tiernap** [comment]
hi thank you for the merge.

regarding your question above, yes roundcube has already defined a default (empty) for plugins array in defaults.inc.php , so i would think it bad protocol to redefine again empty in config.inc.php .

i have also tested it and it works as expected without it in config.inc.php

**Comment by tohuwabohu** [comment]
I've release this as 3.3.0 to the forge, thanks for the contribution.

**Comment by oxc** [comment]
This actually broke my use-case of not using the main $plugins parameter at all but using roundcube::plugin class directly, as the README suggests (notice the "instead" in _you should declare a roundcube::plugin resource instead_) . This is a breaking change.

In fact, when using the module like this, it even creates an invalid configuration file:

Instead of 
```php
$config['temp_dir'] = '/tmp/roundcube';
$config['plugins'] = array(
   'managesieve',
);
```

it now produces:
```php
$config['temp_dir'] = '/tmp/roundcube';
  'managesieve',
```

**Comment by tohuwabohu** [comment]
Ah dang, appologies. I'll prepare a new release with a fix.

**Comment by oxc** [comment]
Actually, this even prevents using custom configuration of modules at all, unless you specify at least one plugin with default configuration in the $plugins param.

**Comment by tiernap** [comment]
apologies also, let me know if i can do anything to help (without breaking it further)

**Comment by oxc** [comment]
@tohuwabohu thanks, the new version runs fine with my existing config. Thanks for the quick fix!

**Comment by tiernap** [comment]
@tohuwabohu i think it works perfectly also for my use case

thank you! that is awesome work. i expected you to revert my change but you have fixed it for all

have a great day!

**Pull request merged**
